[build]
  bin = "app"
  cmd = "go build -o ./tmp/main ."
  full_bin = "./tmp/main"
  include_ext = ["go"]
  exclude_dir = ["vendor"]
  exclude_ext = ["swp", "md"]
  exclude_file = []
  exclude_regex = ["_test.go"]

[log]
  level = "debug"
  color = "true"

[run]
  cmd = "./tmp/main"
  watch_dir = ["."]
  watch_delay = 200 # milliseconds