version: '3.8'

services:
  api:
    container_name: myapi
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/app
      - /app/vendor
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - GO_ENV=development
      - AIR_GO_FLAGS=-mod=vendor

  web:
    container_name: myweb
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web:/web
      - /web/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true

  redis:
    container_name: myredis
    image: redis:alpine
    ports:
      - "6379:6379"