version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/vendor
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - GO_ENV=development
      - AIR_GO_FLAGS=-mod=vendor
    command: air

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"